- hosts: "{{ env }}"
  become: yes
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root/
  - name: create pods in kubernetes objects     
    command: kubectl apply -f /root/deployment.yaml 
  - name: key to create secret
    command: sh /root/key
     
      
