- hosts: "{{ env }}"
  become: yes
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root/
  - name: copy namespace file to kubernetes master 
    copy:
      src: namespace.yaml
      dest: /root/
  - name: delete previous deployment in  kubernetes objects     
    command: kubectl delete -f /root/deployment.yaml
  - name: delete previous namespace in  kubernetes objects     
    command: kubectl delete -f /root/namespace.yaml
  - name: create current namespace in  kubernetes objects     
    command: kubectl apply -f /root/namespace.yaml
  - name: key to create secret
    command: sh /root/key
  - name: create current deployment in  kubernetes objects     
    command: kubectl apply -f /root/deployment.yaml
     
      
