- hosts: "{{ env }}"
  become: yes
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root/
  - name: delete the previous of kubernetes objects     
    command: kubectl apply -f /root/deployment.yaml  
     
      
