   
kind: Deployment
apiVersion: apps/v1
metadata:
  name: softspace
  namespace: febnamespace
spec:
  replicas: 6
  minReadySeconds: 45 # wait for 45 sec before going to deploy next pod
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2        # max number of pods to run for the deployment
  selector:
    matchLabels:
      app: softapp
  template:
    metadata:
      name: softspace
      labels:
        app: softapp
    spec:
      containers:
       - name: softapp
         image: sibinvin/tango:latest
      imagePullSecrets:
       - name: mysecret

---
kind: Service
apiVersion: v1
metadata:
   name: softapp-svc
   namespace: febnamespace
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: softapp


    
    


